const hostData = [
  {
    id: 'aaaaa',
    name: 'herrr',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'gyeongju',
    detail: '짱짱 멋진 숙소',
  },
  {
    id: 'bbbbb',
    name: 'zzang',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeonju',
    detail: '짱짱 예쁜 숙소',
  },

  {
    id: 'ddddd',
    name: 'geegee',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeju',
    detail: '오션뷰 짱🌅',
  },
  {
    id: 'eeeee',
    name: 'hehe',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeju',
    detail: '짱짱 멋진 숙소',
  },
  {
    id: 'eeeee',
    name: 'hehe',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'busan',
    detail: '짱짱 좋은 숙소',
  },
  {
    id: 'fff',
    name: 'omg',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'busan',
    detail: '짱짱 예쁜 숙소',
  },
  {
    id: 'gsdhff',
    name: 'ananti',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'busan',
    detail: '짱짱 비싼 숙소',
  },
  {
    id: 'gggggg',
    name: 'haohaohao',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeonju',
    detail: '전주비빔밥 콩나물해장국 공짜!',
  },
  {
    id: 'hhhhhh',
    name: 'huahuahua',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'gyeongju',
    detail: '경주에서 제일 커요',
  },
  {
    id: 'iiiii',
    name: 'kekeke',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'busan',
    detail: '주변에 핫플레이스가 있어요',
  },
  {
    id: 'jjjjj',
    name: 'hahaha',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeju',
    detail: '조식이 맛있어요',
  },
  {
    id: 'kkkkk',
    name: 'cooold',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeju',
    detail: '반려견 운동장이 있어요🦮',
  },
  {
    id: 'lllll',
    name: 'cooold',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeonju',
    detail: '공기가 맑아요',
  },
  {
    id: 'm',
    name: 'mstyle',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeonju',
    detail: '공기가 맑아요',
  },
  {
    id: 'nmnmnmn',
    name: 'g0',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'gyeongju',
    detail: '한옥이 멋져요',
  },
  {
    id: 'ooooh',
    name: 'g0',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'gyeongju',
    detail: '한옥이 멋져요',
  },
  {
    id: 'piiiiii',
    name: 'orange',
    picture: 'https://avatars.githubusercontent.com/u/131247158?v=4',
    location: 'jeju',
    detail: '제주감귤 무제한 서비스🍊',
  },
];
export default hostData;
